/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental_car_project;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahkam
 */
public class Car_Rental_Information extends javax.swing.JFrame {

    /**
     * Creates new form Car_Rental_Information
     */
    public Car_Rental_Information() {
        initComponents();
        loadCategoryID();
        
          txt_customer_ID.setEnabled(false);
        txt_customer_name.setEnabled(false);
        txt_rental_fee.setEnabled(false);
       txt_Issue_Date.setEnabled(false);
       txt_Due_Date.setEnabled(false);
       
       
       
          txt_Issue_Date.setDateFormatString("yyyy/MM/dd");
        txt_Due_Date.setDateFormatString("yyyy/MM/dd");
    }
    
    Connection connect1;
    PreparedStatement prest1;
    PreparedStatement prest2;
    PreparedStatement prest3;
    PreparedStatement prest4;
    
    
    
         public void loadCategoryID()
                    {
                        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect1 = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
            
            
            
            
            prest1 = connect1.prepareStatement("select * from car_registration");
            
            
            
            ResultSet  rs = prest1.executeQuery();
            
            Combo_Car_ID.removeAllItems();
            
            while(rs.next())
            {
                Combo_Car_ID.addItem(rs.getString(2 ));
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
        } 
           
                        
         }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Car_available_status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_customer_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_customer_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_rental_fee = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        OK_Button = new javax.swing.JButton();
        Cancel_Button = new javax.swing.JButton();
        Combo_Car_ID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Rental Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jLabel1.setText("Car ID");

        jLabel2.setText("Customer ID");

        txt_customer_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_customer_IDActionPerformed(evt);
            }
        });
        txt_customer_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_customer_IDKeyPressed(evt);
            }
        });

        jLabel3.setText("Cuistomer Name");
        jLabel3.setOpaque(true);

        jLabel4.setText("Rental Fee");

        jLabel5.setText("Isue Date");

        jLabel6.setText("Due Date");

        OK_Button.setText("OK");
        OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_ButtonActionPerformed(evt);
            }
        });

        Cancel_Button.setText("Cancel");
        Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_ButtonActionPerformed(evt);
            }
        });

        Combo_Car_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Car_IDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_customer_ID)
                            .addComponent(txt_customer_name)
                            .addComponent(txt_rental_fee)
                            .addComponent(Combo_Car_ID, 0, 131, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(txt_Car_available_status, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Cancel_Button)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Car_available_status, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Combo_Car_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_customer_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_rental_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_ButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_Cancel_ButtonActionPerformed

    private void OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_ButtonActionPerformed
           try {
          
            String car_id = Combo_Car_ID.getSelectedItem().toString();
            
            String customer_id  = txt_customer_ID.getText();
      
            String car_rent_fee= txt_rental_fee.getText();
            
                       
            SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
            String issue_date = date_format.format(txt_Issue_Date.getDate());
            
            
            SimpleDateFormat date_format1 = new SimpleDateFormat("yyyy-MM-dd");
            String due_date = date_format1.format(txt_Due_Date.getDate());
            
            Class.forName("com.mysql.jdbc.Driver"); 
            connect1 = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
            
           prest4 = connect1.prepareStatement("insert into rental(car_id, cust_id, fee, date, due) values(?,?,?,?,?)");
           
           prest4.setString(1, car_id);
           prest4.setString(2, customer_id);
           prest4.setString(3, car_rent_fee);
           prest4.setString(4, issue_date);
            prest4.setString(5, due_date);
            
            prest4.executeUpdate();
            
            
            prest4 = connect1.prepareStatement("update car_registration set available='no' where car_no=?");
           
           prest4.setString(1, car_id);
            
            prest4.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Car is booked");
            
         
           
          txt_customer_ID.setText("");
          txt_customer_name.setText("");
          txt_rental_fee.setText("");
       
          
            
        txt_customer_ID.setEnabled(false);
        txt_customer_name.setEnabled(false);
        txt_rental_fee.setEnabled(false);
       txt_Issue_Date.setEnabled(false);
       txt_Due_Date.setEnabled(false); 
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_OK_ButtonActionPerformed

    private void Combo_Car_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Car_IDActionPerformed
       
        
         try {
           
            
            
            String car_id = Combo_Car_ID.getSelectedItem().toString();
            
            Class.forName("com.mysql.jdbc.Driver");
            connect1 = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
            
            
            
            prest2 = connect1.prepareStatement("select * from car_registration where car_no=?");
            
            prest2.setString(1, car_id);
            
          ResultSet  rs = prest2.executeQuery();
            
            
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this, "Car number is not Found");
            }
            else
            {
                String available_status = rs.getString("available");
                txt_Car_available_status.setText(available_status.trim());
                
                
                
                
                if(available_status.equals("yes"))
                {
                    
                    txt_customer_ID.setEnabled(true);
        txt_customer_name.setEnabled(true);
        txt_rental_fee.setEnabled(true);
       txt_Issue_Date.setEnabled(true);
       txt_Due_Date.setEnabled(true);
        
                    
                }
                 if(available_status.equals("no"))
                {
                    
                    txt_customer_ID.setEnabled(false);
        txt_customer_name.setEnabled(false);
        txt_rental_fee.setEnabled(false);
       txt_Issue_Date.setEnabled(false);
       txt_Due_Date.setEnabled(false);
        
                    
                }
                
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Combo_Car_IDActionPerformed

    private void txt_customer_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_customer_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_customer_IDActionPerformed

    private void txt_customer_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_customer_IDKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try {
                String customer_id = txt_customer_ID.getText();
                
                Class.forName("com.mysql.jdbc.Driver");
                connect1 = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                
                prest3 = connect1.prepareStatement("select * from customer where cust_id=?");
                prest3.setString(1, customer_id);
             ResultSet   rs= prest3.executeQuery();
                
               if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this, "Customer is not Found");
            }
            else
            {
                String customer_name = rs.getString("customer_name");
                txt_customer_name.setText(customer_name.trim());
            }    
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Car_Rental_Information.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_txt_customer_IDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car_Rental_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car_Rental_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car_Rental_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car_Rental_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car_Rental_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JComboBox<String> Combo_Car_ID;
    private javax.swing.JButton OK_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Car_available_status;
    private javax.swing.JTextField txt_customer_ID;
    private javax.swing.JTextField txt_customer_name;
    private javax.swing.JTextField txt_rental_fee;
    // End of variables declaration//GEN-END:variables
}
