/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental_car_project;

/**
 *
 * @author Ahkam
 */
public class Main_Functionality_Rental_System extends javax.swing.JFrame {

    /**
     * Creates new form Main_Functionality_Rental_System
     */
    public Main_Functionality_Rental_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Car_Registration_Button = new javax.swing.JButton();
        Customer_Registration_Button = new javax.swing.JButton();
        Car_Rental_Info_Button = new javax.swing.JButton();
        Return_car_Info_Button = new javax.swing.JButton();
        Log_out_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Feature of Car Rental Management System");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Car_Registration_Button.setText("Car Registration");
        Car_Registration_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Car_Registration_ButtonActionPerformed(evt);
            }
        });

        Customer_Registration_Button.setText("Customer Registration");
        Customer_Registration_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_Registration_ButtonActionPerformed(evt);
            }
        });

        Car_Rental_Info_Button.setText("Car Rental Info");
        Car_Rental_Info_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Car_Rental_Info_ButtonActionPerformed(evt);
            }
        });

        Return_car_Info_Button.setText("Return car Info");
        Return_car_Info_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_car_Info_ButtonActionPerformed(evt);
            }
        });

        Log_out_Button.setText("Log out");
        Log_out_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_out_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Customer_Registration_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Car_Rental_Info_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Return_car_Info_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Log_out_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Car_Registration_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(Car_Registration_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Customer_Registration_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Car_Rental_Info_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Return_car_Info_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Log_out_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Car_Registration_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Car_Registration_ButtonActionPerformed
        // TODO add your handling code here:
        
        Car_Registration_Form car_register = new Car_Registration_Form();
       
        car_register.setVisible(true);
        
    }//GEN-LAST:event_Car_Registration_ButtonActionPerformed

    private void Car_Rental_Info_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Car_Rental_Info_ButtonActionPerformed
        // TODO add your handling code here:
        Car_Rental_Information   car_rent_info = new  Car_Rental_Information();
       
        car_rent_info.setVisible(true);
        
        
    }//GEN-LAST:event_Car_Rental_Info_ButtonActionPerformed

    private void Customer_Registration_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_Registration_ButtonActionPerformed
        // TODO add your handling code here:
        Customer_Registration_Form customer_registration =  new  Customer_Registration_Form();
     
        customer_registration.setVisible(true);
        
    }//GEN-LAST:event_Customer_Registration_ButtonActionPerformed

    private void Return_car_Info_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_car_Info_ButtonActionPerformed
        // TODO add your handling code here:
        Return_Car_Info_Form  return_car = new Return_Car_Info_Form();
        return_car.setVisible(true);
    }//GEN-LAST:event_Return_car_Info_ButtonActionPerformed

    private void Log_out_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_out_ButtonActionPerformed
        // TODO add your handling code here:
        LogIN login = new LogIN();
        login.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_Log_out_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Functionality_Rental_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Functionality_Rental_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Functionality_Rental_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Functionality_Rental_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Functionality_Rental_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Car_Registration_Button;
    private javax.swing.JButton Car_Rental_Info_Button;
    private javax.swing.JButton Customer_Registration_Button;
    private javax.swing.JButton Log_out_Button;
    private javax.swing.JButton Return_car_Info_Button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
